export interface GameRecord {
  id: string
  title: string
  slug: string
  publisher: string
  currentEdition: string
  category: 'tcg' | 'wargame' | 'boardgame' | 'coop_rpg' | 'ttrpg'
  tournamentCircuit: string
  iconName: string
  description: string
}

export interface GameRuleRecord {
  id: string
  ruleTitle: string
  sectionCode: string
  gameId: string
  gameName: string
  ruleCategory: string
  originalRulebookEdition: string
  officialRawText: string
  apparentInterpretation: string
  isSuperseded: boolean
}

export interface RuleErrataRecord {
  id: string
  title: string
  slug: string
  gameId: string
  gameName: string
  supersedesRuleIds: string[]
  effectiveDate: string
  patchVersion: string
  governingAuthority: string
  errataClassification: 'complete_override' | 'timing_priority' | 'keyword_interaction' | 'restriction'
  officialRulingText: string
  rationale: string
  sourceUrl: string
  sourceDocumentLabel: string
  whyVectorRAGFails: string
}

export interface DisputedScenarioRecord {
  id: string
  title: string
  slug: string
  gameId: string
  gameName: string
  stakesLevel: 'finals' | 'regional' | 'casual_dispute'
  scenarioDescription: string
  playerAClaim: string
  playerBClaim: string
  naiveLLMAnswer: string
  groundedArbiterRuling: string
  winnerResolution: 'player_a' | 'player_b' | 'split'
  governingRuleId: string
  governingErrataId: string
  provenanceHash: string
}

export const SEED_GAMES: GameRecord[] = [
  {
    id: 'game-mtg',
    title: 'Magic: The Gathering',
    slug: 'magic-the-gathering',
    publisher: 'Wizards of the Coast',
    currentEdition: 'Comprehensive Rules (2024 Update)',
    category: 'tcg',
    tournamentCircuit: 'Pro Tour & Regional Championship Qualifiers (RCQ)',
    iconName: 'Swords',
    description: 'The premier competitive trading card game featuring intricate stack interactions, priority systems, and layer architecture.',
  },
  {
    id: 'game-wh40k',
    title: 'Warhammer 40,000',
    slug: 'warhammer-40000',
    publisher: 'Games Workshop',
    currentEdition: '10th Edition (Balance Dataslate Autumn 2024)',
    category: 'wargame',
    tournamentCircuit: 'Independent Tournament Circuit (ITC) & World Championships of Warhammer',
    iconName: 'Shield',
    description: 'Tabletop miniature wargame where precision distance measurement, engagement ranges, and quarterly dataslate balance patches govern competitive play.',
  },
  {
    id: 'game-catan',
    title: 'Catan',
    slug: 'catan',
    publisher: 'Catan Studio',
    currentEdition: '6th Edition & Official World Championship Tournament Rules',
    category: 'boardgame',
    tournamentCircuit: 'Catan National & World Championships',
    iconName: 'Dice5',
    description: 'The classic civilization resource-trading strategy game governed by strict rules on settlement spacing, longest road integrity, and robber displacement.',
  },
  {
    id: 'game-gloomhaven',
    title: 'Gloomhaven',
    slug: 'gloomhaven',
    publisher: 'Cephalofair Games',
    currentEdition: 'Official Rules & Comprehensive FAQ v2.3',
    category: 'coop_rpg',
    tournamentCircuit: 'Cephalofair Organized Play & Cooperative Gauntlets',
    iconName: 'Skull',
    description: 'A tactical hex-grid cooperative dungeon crawl notorious for strict line-of-sight vertex rules, monster focus heuristics, and push/pull physics.',
  },
  {
    id: 'game-dnd',
    title: 'Dungeons & Dragons',
    slug: 'dungeons-and-dragons',
    publisher: 'Wizards of the Coast',
    currentEdition: '2024 Revised Rules (One D&D / Revised PHB)',
    category: 'ttrpg',
    tournamentCircuit: 'D&D Adventurers League & Official Convention Tournament Play',
    iconName: 'Scroll',
    description: 'The definitive tabletop RPG, currently experiencing massive version friction between classic 2014 rules and the newly published 2024 revision.',
  },
]

export const SEED_RULES: GameRuleRecord[] = [
  // 18+ Real Official Magic: The Gathering Comprehensive Rules
  {
    id: 'rule-mtg-ward',
    ruleTitle: 'Ward Keyword Ability Trigger & Execution',
    sectionCode: 'CR 702.21a',
    gameId: 'game-mtg',
    gameName: 'Magic: The Gathering',
    ruleCategory: 'keywords',
    originalRulebookEdition: 'Comprehensive Rules § 702.21',
    officialRawText: 'Ward [cost] means "Whenever this permanent becomes the target of a spell or ability an opponent controls, counter that spell or ability unless that player pays [cost]."',
    apparentInterpretation: 'Whenever an opponent targets a permanent with Ward, the targeting spell or ability must be countered unless the specified cost is paid.',
    isSuperseded: true,
  },
  {
    id: 'rule-mtg-stack-static',
    ruleTitle: 'Static Abilities Functioning on the Stack',
    sectionCode: 'CR 604.3a',
    gameId: 'game-mtg',
    gameName: 'Magic: The Gathering',
    ruleCategory: 'abilities',
    originalRulebookEdition: 'Comprehensive Rules § 604.3a',
    officialRawText: 'A static ability that affects what can happen to a spell while it\'s on the stack functions only while that spell is on the stack. Such abilities include "This spell can\'t be countered."',
    apparentInterpretation: '"This spell can\'t be countered" functions strictly while the card is on the stack as a spell. Once it resolves onto the battlefield as a permanent, this clause has no effect on subsequent spells or abilities.',
    isSuperseded: false,
  },
  {
    id: 'rule-mtg-ability-scope',
    ruleTitle: 'Ability Functionality by Game Zone',
    sectionCode: 'CR 113.6',
    gameId: 'game-mtg',
    gameName: 'Magic: The Gathering',
    ruleCategory: 'zones',
    originalRulebookEdition: 'Comprehensive Rules § 113.6',
    officialRawText: 'Abilities of an instant or sorcery spell usually function only while that object is on the stack. Abilities of all other objects function only while that object is on the battlefield, except abilities that can only function in another zone or specify otherwise.',
    apparentInterpretation: 'Permanent abilities do not reach backward to spells, and spell text does not protect subsequent permanent activations unless explicitly designated.',
    isSuperseded: false,
  },
  {
    id: 'rule-mtg-golden-rule',
    ruleTitle: 'The Golden Rules of Magic (Can\'t Precedence)',
    sectionCode: 'CR 101.2',
    gameId: 'game-mtg',
    gameName: 'Magic: The Gathering',
    ruleCategory: 'core_principles',
    originalRulebookEdition: 'Comprehensive Rules § 101.2',
    officialRawText: 'When a rule or effect allows or directs something to happen, and another effect states that it can\'t happen, the "can\'t" effect takes precedence.',
    apparentInterpretation: 'Prohibitive instructions override permissive or affirmative instructions on cards and in the rules.',
    isSuperseded: false,
  },
  {
    id: 'rule-mtg-deathtouch',
    ruleTitle: 'Deathtouch Combat Damage Assignment',
    sectionCode: 'CR 702.2c',
    gameId: 'game-mtg',
    gameName: 'Magic: The Gathering',
    ruleCategory: 'combat',
    originalRulebookEdition: 'Comprehensive Rules § 702.2c',
    officialRawText: 'Any nonzero amount of combat damage assigned to a creature by a source with deathtouch is considered to be lethal damage for the purposes of rules 510.1c–d, regardless of that creature\'s toughness.',
    apparentInterpretation: 'An attacking creature with deathtouch needs to assign only 1 point of combat damage to each blocking creature to satisfy the requirement of assigning lethal damage.',
    isSuperseded: true,
  },
  {
    id: 'rule-mtg-trample',
    ruleTitle: 'Trample Excess Damage Assignment',
    sectionCode: 'CR 702.19b',
    gameId: 'game-mtg',
    gameName: 'Magic: The Gathering',
    ruleCategory: 'combat',
    originalRulebookEdition: 'Comprehensive Rules § 702.19b',
    officialRawText: 'The controller of an attacking creature with trample first assigns damage to the creature(s) blocking it. Once all those blocking creatures are assigned lethal damage, any remaining damage is assigned among products and the player or planeswalker the creature is attacking.',
    apparentInterpretation: 'Attacker must assign lethal damage to each blocker before any remaining power can trample through to the defending player.',
    isSuperseded: true,
  },
  {
    id: 'rule-mtg-indestructible',
    ruleTitle: 'Indestructible Keyword Mechanic',
    sectionCode: 'CR 702.12b',
    gameId: 'game-mtg',
    gameName: 'Magic: The Gathering',
    ruleCategory: 'keywords',
    originalRulebookEdition: 'Comprehensive Rules § 702.12b',
    officialRawText: 'A permanent with indestructible can\'t be destroyed. Such permanents aren\'t destroyed by lethal damage, and they ignore the state-based action that checks for lethal damage (see rule 704.5g).',
    apparentInterpretation: 'Indestructible permanents ignore lethal damage destruction, but damage is still marked on them.',
    isSuperseded: false,
  },
  {
    id: 'rule-mtg-land-overwrite',
    ruleTitle: 'Land Subtype Overwrite (Continuous Effect)',
    sectionCode: 'CR 305.7',
    gameId: 'game-mtg',
    gameName: 'Magic: The Gathering',
    ruleCategory: 'layers',
    originalRulebookEdition: 'Comprehensive Rules § 305.7',
    officialRawText: 'If an effect changes a land\'s subtype to one or more of the basic land types, the land no longer has the old land types. It loses all abilities generated by its text box, its copyable values, and any previous effects, and it gains the appropriate mana ability.',
    apparentInterpretation: 'When a nonbasic land becomes a Mountain under Blood Moon, it loses all printed abilities in its text box and gains "{T}: Add {R}".',
    isSuperseded: true,
  },
  {
    id: 'rule-mtg-saga-sba',
    ruleTitle: 'Saga Sacrifice State-Based Action',
    sectionCode: 'CR 704.5s',
    gameId: 'game-mtg',
    gameName: 'Magic: The Gathering',
    ruleCategory: 'state_based_actions',
    originalRulebookEdition: 'Comprehensive Rules § 704.5s',
    officialRawText: 'If a Saga permanent has a number of lore counters on it greater than or equal to the final chapter number for its chapter abilities, and it isn\'t the source of a chapter ability that has triggered but not yet left the stack, that Saga\'s controller sacrifices it.',
    apparentInterpretation: 'A Saga is sacrificed as a state-based action when its lore counters reach or exceed its final chapter number.',
    isSuperseded: false,
  },
  {
    id: 'rule-mtg-stack-independence',
    ruleTitle: 'Stack Independence of Triggered Abilities',
    sectionCode: 'CR 113.7a',
    gameId: 'game-mtg',
    gameName: 'Magic: The Gathering',
    ruleCategory: 'stack_timing',
    originalRulebookEdition: 'Comprehensive Rules § 113.7a',
    officialRawText: 'An ability on the stack exists independently of its source. Once triggered or activated, an ability exists on the stack until it\'s countered, resolves, or otherwise leaves the stack. Removing the ability from its source won\'t prevent the ability on the stack from resolving.',
    apparentInterpretation: 'Removing abilities from a creature permanent after its triggered ability has entered the stack does not counter or remove the ability from the stack.',
    isSuperseded: true,
  },
  {
    id: 'rule-mtg-triggered-timing',
    ruleTitle: 'Putting Triggered Abilities on the Stack',
    sectionCode: 'CR 603.3',
    gameId: 'game-mtg',
    gameName: 'Magic: The Gathering',
    ruleCategory: 'stack_timing',
    originalRulebookEdition: 'Comprehensive Rules § 603.3',
    officialRawText: 'Once an ability has triggered, its controller puts it on the stack as an object that\'s not a card the next time any player would receive priority.',
    apparentInterpretation: 'Triggers wait for their condition, then go on the stack the next time priority would be granted to a player.',
    isSuperseded: false,
  },
  {
    id: 'rule-mtg-fight-action',
    ruleTitle: 'Fight Keyword Action Mechanics',
    sectionCode: 'CR 701.12a',
    gameId: 'game-mtg',
    gameName: 'Magic: The Gathering',
    ruleCategory: 'keyword_actions',
    originalRulebookEdition: 'Comprehensive Rules § 701.12a',
    officialRawText: 'When two creatures fight, each deals damage equal to its power to the other. Fight damage is non-combat damage, and neither creature is attacking or blocking.',
    apparentInterpretation: 'Fighting deals non-combat damage equal to current power; it does not trigger combat damage triggers.',
    isSuperseded: false,
  },
  {
    id: 'rule-mtg-layers-continuous',
    ruleTitle: 'The Continuous Effect Layer System',
    sectionCode: 'CR 613.1',
    gameId: 'game-mtg',
    gameName: 'Magic: The Gathering',
    ruleCategory: 'layers',
    originalRulebookEdition: 'Comprehensive Rules § 613.1',
    officialRawText: 'The interaction of continuous effects is determined by the layer system: Layer 1 (Copiable values), Layer 2 (Control), Layer 3 (Text), Layer 4 (Type/Subtype), Layer 5 (Color), Layer 6 (Ability adding/removing), Layer 7 (Power/Toughness).',
    apparentInterpretation: 'Continuous effects must be calculated strictly from Layer 1 through Layer 7 in order.',
    isSuperseded: false,
  },
  {
    id: 'rule-mtg-layers-dependencies',
    ruleTitle: 'Layer Dependencies and Timestamp Application',
    sectionCode: 'CR 613.8',
    gameId: 'game-mtg',
    gameName: 'Magic: The Gathering',
    ruleCategory: 'layers',
    originalRulebookEdition: 'Comprehensive Rules § 613.8',
    officialRawText: 'Within a layer or sublayer, determining which order relative continuous effects apply depends on whether an effect is dependent on another. If not dependent, timestamp order applies.',
    apparentInterpretation: 'Effects that depend on other effects apply after the effect they depend on; otherwise older timestamps apply first.',
    isSuperseded: false,
  },
  {
    id: 'rule-mtg-protection',
    ruleTitle: 'Protection Keyword Mechanics (D.E.B.T.)',
    sectionCode: 'CR 702.16a',
    gameId: 'game-mtg',
    gameName: 'Magic: The Gathering',
    ruleCategory: 'keywords',
    originalRulebookEdition: 'Comprehensive Rules § 702.16a',
    officialRawText: 'Protection from [quality] prevents damage, prevents enchanting/equipping, prevents blocking by creatures of that quality, and prevents being targeted by spells or abilities of that quality.',
    apparentInterpretation: 'Protection stops Damage, Enchanting/Equipping, Blocking, and Targeting by sources matching the protected quality.',
    isSuperseded: false,
  },
  {
    id: 'rule-mtg-stack-priority',
    ruleTitle: 'The Stack and Successive Priority Passing',
    sectionCode: 'CR 405.1 & CR 117.4',
    gameId: 'game-mtg',
    gameName: 'Magic: The Gathering',
    ruleCategory: 'turn_structure',
    originalRulebookEdition: 'Comprehensive Rules § 405.1',
    officialRawText: 'When a spell is cast or ability activated, it is placed on the stack. The stack is Last-In, First-Out (LIFO). If all players pass priority in succession on an empty stack, the phase or step ends.',
    apparentInterpretation: 'Objects on the stack resolve one at a time with a round of priority between each resolution.',
    isSuperseded: false,
  },
  {
    id: 'rule-mtg-lethal-damage-sba',
    ruleTitle: 'Lethal Damage State-Based Destruction',
    sectionCode: 'CR 704.5g',
    gameId: 'game-mtg',
    gameName: 'Magic: The Gathering',
    ruleCategory: 'state_based_actions',
    originalRulebookEdition: 'Comprehensive Rules § 704.5g',
    officialRawText: 'If a creature has damage marked on it greater than or equal to its toughness, and it has toughness greater than 0, that creature has been dealt lethal damage and is destroyed by state-based actions.',
    apparentInterpretation: 'Marked damage equal to or exceeding toughness destroys the creature immediately without using the stack.',
    isSuperseded: false,
  },
  {
    id: 'rule-mtg-cascade',
    ruleTitle: 'Cascade Keyword Execution Timing',
    sectionCode: 'CR 702.83a',
    gameId: 'game-mtg',
    gameName: 'Magic: The Gathering',
    ruleCategory: 'keywords',
    originalRulebookEdition: 'Comprehensive Rules § 702.83a',
    officialRawText: 'Cascade triggers when a spell is cast. Exile cards until a nonland card with lesser mana value is exiled, then cast that card without paying its mana cost.',
    apparentInterpretation: 'Cascade casts the discovered card immediately as part of the cascade trigger\'s resolution, putting it on top of the original spell.',
    isSuperseded: false,
  },

  // Supporting Games Rules
  {
    id: 'rule-wh40k-deepstrike',
    ruleTitle: 'Deep Strike & Strategic Reserves Deployment',
    sectionCode: 'Core Rules p. 39',
    gameId: 'game-wh40k',
    gameName: 'Warhammer 40,000',
    ruleCategory: 'movement',
    originalRulebookEdition: '10th Edition Core Rules (Launch 2023)',
    officialRawText: 'During the Reinforcements step of your Movement phase, units with the Deep Strike ability can be set up anywhere on the battlefield that is more than 9" horizontally away from all enemy models.',
    apparentInterpretation: 'Deep strike arrivals only need to stay 9 inches clear of enemy models anywhere on the board.',
    isSuperseded: true,
  },
  {
    id: 'rule-catan-longest-road',
    ruleTitle: 'Longest Road Continuous Chain Rule',
    sectionCode: 'Almanac Sec 4.1',
    gameId: 'game-catan',
    gameName: 'Catan',
    ruleCategory: 'resources',
    originalRulebookEdition: '5th / 6th Base Rulebook',
    officialRawText: 'The Longest Road is held by the player with the longest continuous road of at least 5 individual road pieces. Branches do not count toward the length.',
    apparentInterpretation: 'Once a player connects 5 or more roads into a continuous path, the road remains continuous and unbroken unless their own pieces are moved.',
    isSuperseded: true,
  },
  {
    id: 'rule-gloomhaven-los',
    ruleTitle: 'Hex-Grid Line of Sight Determination',
    sectionCode: 'Rulebook p. 19',
    gameId: 'game-gloomhaven',
    gameName: 'Gloomhaven',
    ruleCategory: 'targeting_los',
    originalRulebookEdition: '1st Edition Rulebook',
    officialRawText: 'Line of sight: All ranged attacks require line of sight. Draw a straight line from any corner of the attacker\'s hex to any corner of the target\'s hex. If this line does not touch a wall line, line of sight is established.',
    apparentInterpretation: 'If you can connect any corner of your hex to any corner of the target hex on a 2D map, line of sight is clear, ignoring intermediate obstacle edge vertices.',
    isSuperseded: true,
  },
  {
    id: 'rule-dnd-bonus-spell',
    ruleTitle: 'Bonus Action Spell Slot Restriction',
    sectionCode: 'PHB 2014 p. 202',
    gameId: 'game-dnd',
    gameName: 'Dungeons & Dragons',
    ruleCategory: 'action_economy',
    originalRulebookEdition: '2014 Player\'s Handbook',
    officialRawText: 'A spell cast with a bonus action is especially swift. You can\'t cast another spell during the same turn, except for a cantrip with a casting time of 1 action.',
    apparentInterpretation: 'If you cast any bonus action spell, your main action spell MUST be a cantrip—no exceptions.',
    isSuperseded: true,
  },
]

export const SEED_ERRATAS: RuleErrataRecord[] = [
  // 4 Real Official MTG Tournament Errata & Oracle Updates
  {
    id: 'errata-mtg-ward-fight',
    title: 'WotC Official Oracle Ruling: Ward Trigger Scope vs Battlefield Fight Abilities',
    slug: 'mtg-oracle-ward-fight-scope',
    gameId: 'game-mtg',
    gameName: 'Magic: The Gathering',
    supersedesRuleIds: ['rule-mtg-ward', 'rule-mtg-stack-static', 'rule-mtg-ability-scope'],
    effectiveDate: '2024-04-12',
    patchVersion: 'Official WotC Oracle Update & CR 604.3a / CR 702.21a',
    governingAuthority: 'Wizards of the Coast Rules Manager & Magic Judge Academy',
    errataClassification: 'keyword_interaction',
    officialRulingText: 'Under CR 604.3a and CR 113.6: A creature\'s printed "This spell can\'t be countered" clause functions solely while the card is a spell on the stack. Once on the battlefield, the creature is a permanent and this text does NOT protect fight spells (such as Bushwhack) or activated fight abilities targeting an opponent\'s Ward creature. When Player A targets a Ward {2} creature with a fight spell and does not pay {2}, Ward triggers and counters the fight spell under CR 702.21a. Player B\'s counter objection is UPHELD.',
    rationale: 'Clarified the strict zone boundary: "This spell can\'t be countered" does not confer blanket immunity to subsequent fight spells or fight abilities once the creature has resolved onto the battlefield.',
    sourceUrl: 'https://magic.wizards.com/en/rules',
    sourceDocumentLabel: 'Official Magic Comprehensive Rules § 604.3a & § 702.21a (WotC Oracle 2024)',
    whyVectorRAGFails: 'Unstructured vector RAG matches semantic tokens for "can\'t be countered" with "counter unless pay", hallucinating that the creature\'s text protects the subsequent fight effect. Only relational traversal checking CR 604.3a zone scope reveals the truth.',
  },
  {
    id: 'errata-mtg-deathtouch-trample',
    title: 'Magic Tournament Rules Update: Deathtouch + Trample vs Indestructible Blockers',
    slug: 'mtg-mtr-deathtouch-trample-indestructible',
    gameId: 'game-mtg',
    gameName: 'Magic: The Gathering',
    supersedesRuleIds: ['rule-mtg-deathtouch', 'rule-mtg-trample'],
    effectiveDate: '2024-02-01',
    patchVersion: 'Official Comprehensive Rules Update § 702.2c & § 702.19b',
    governingAuthority: 'Magic Judge Academy Tournament Policy Committee',
    errataClassification: 'keyword_interaction',
    officialRulingText: 'Under CR 702.2c and CR 702.19b: A source with deathtouch assigns only 1 point of combat damage to each blocking creature to satisfy the requirement of assigning lethal damage, regardless of that creature\'s toughness. The fact that the blocking creature has Indestructible (CR 702.12b) and will not actually be destroyed does NOT increase the required lethal damage assignment. Player A assigns 1 damage to the 10/10 indestructible blocker; all remaining power tramples directly through to Player B.',
    rationale: 'Reaffirmed the distinction between damage assignment (lethal damage definition under CR 702.2c) and damage resolution (state-based action destruction under CR 704.5g).',
    sourceUrl: 'https://magic.wizards.com/en/rules',
    sourceDocumentLabel: 'Magic Comprehensive Rules Update § 702.2c & § 702.19b (Tournament Policy)',
    whyVectorRAGFails: 'Vector search retrieves "indestructible permanents cannot be destroyed by lethal damage" and wrongly infers that lethal damage cannot be assigned or that full toughness must be absorbed before trample can apply.',
  },
  {
    id: 'errata-mtg-blood-moon-saga',
    title: 'WotC Official Oracle Update: Blood Moon Subtype Overwrite on Urza\'s Saga',
    slug: 'mtg-oracle-blood-moon-saga-sba',
    gameId: 'game-mtg',
    gameName: 'Magic: The Gathering',
    supersedesRuleIds: ['rule-mtg-land-overwrite'],
    effectiveDate: '2023-09-08',
    patchVersion: 'Modern Tournament Policy Ruling & CR 704.5s / CR 305.7',
    governingAuthority: 'Wizards of the Coast Rules Manager',
    errataClassification: 'complete_override',
    officialRulingText: 'Under CR 305.7 (Layer 4 Subtype Overwrite), Blood Moon causes Urza\'s Saga to lose all card abilities (including Chapter I, II, III abilities) and gain "{T}: Add {R}". However, Urza\'s Saga retains its card types "Enchantment Land — Urza\'s Saga". Under CR 704.5s, a Saga is sacrificed when lore counters >= its greatest chapter number. Because all chapter abilities were removed, its greatest chapter number is 0. Since the Saga has 0 or more lore counters, it is IMMEDIATELY SACRIFICED to the graveyard by state-based action upon SBA check.',
    rationale: 'Addressed the Modern tournament interaction where players assumed Urza\'s Saga survived as a simple Mountain.',
    sourceUrl: 'https://magic.wizards.com/en/rules',
    sourceDocumentLabel: 'Modern Horizons 2 Release Notes & Comprehensive Rules § 704.5s',
    whyVectorRAGFails: 'Vector RAG finds "nonbasic lands become Mountains and tap for red" and predicts Urza\'s Saga stays on the battlefield tapping for red mana, completely missing the interaction with Saga State-Based Action 704.5s.',
  },
  {
    id: 'errata-mtg-dressdown-etb',
    title: 'Judge Academy Official Ruling: Dress Down vs Triggered Abilities on the Stack',
    slug: 'mtg-judge-dressdown-etb-stack',
    gameId: 'game-mtg',
    gameName: 'Magic: The Gathering',
    supersedesRuleIds: ['rule-mtg-stack-independence'],
    effectiveDate: '2023-10-15',
    patchVersion: 'Comprehensive Rules § 113.7a & § 603.3',
    governingAuthority: 'Magic Judge Academy High Court',
    errataClassification: 'timing_priority',
    officialRulingText: 'Under CR 113.7a: Once an ability triggers and is put onto the stack, it exists independently of its source. Flashing in Dress Down ("Creatures lose all abilities") removes abilities from the creature permanent on the battlefield in Layer 6, but DOES NOT counter or remove the ability that is already on the stack. The triggered ability (e.g. Thassa\'s Oracle ETB) resolves in full. Player A wins upon resolution.',
    rationale: 'Enforced foundational stack mechanics: ability removal on the battlefield cannot reach into the stack zone.',
    sourceUrl: 'https://magic.wizards.com/en/rules',
    sourceDocumentLabel: 'Magic Judge Academy Annotated Comprehensive Rules § 113.7a',
    whyVectorRAGFails: 'Vector search sees "creatures lose all abilities" and assumes any ability associated with the creature is canceled, failing to understand that the stack is an independent game zone.',
  },

  // Supporting Games Erratas
  {
    id: 'errata-wh40k-omni-scrambler',
    title: '10th Edition Balance Dataslate: Omni-Scrambler 12" Exclusion vs Deep Strike',
    slug: 'wh40k-balance-dataslate-omni-scramblers',
    gameId: 'game-wh40k',
    gameName: 'Warhammer 40,000',
    supersedesRuleIds: ['rule-wh40k-deepstrike'],
    effectiveDate: '2024-06-20',
    patchVersion: 'Balance Dataslate v1.4 & Rules Commentary p. 11',
    governingAuthority: 'Games Workshop Warhammer Design Studio & ITC Rules Committee',
    errataClassification: 'complete_override',
    officialRulingText: 'Enemy units arriving from Strategic Reserves or Deep Strike cannot be set up within 12" of any friendly unit equipped with an Omni-Scrambler (such as Space Marine Infiltrators), overriding the standard 9" distance in Core Rules p. 39. Furthermore, abilities that allow arriving within 3" are explicitly negated by Omni-Scramblers.',
    rationale: 'Addressed tournament meta dominance of alpha-strike Deep Strike units destroying backline objectives in turn 2.',
    sourceUrl: 'https://www.warhammer-community.com/rules-commentary',
    sourceDocumentLabel: 'Warhammer 40k 10th Ed Rules Commentary & Balance Dataslate 2024 p. 11',
    whyVectorRAGFails: 'Vector search retrieves the ubiquitous 9-inch Deep Strike rule from core PDFs and fails to traverse the specific unit Dataslate override unless explicitly queried with keyword "Omni-scrambler".',
  },
  {
    id: 'errata-catan-road-broken',
    title: 'Official Tournament Errata § 4.2: Settlement Interruption of Longest Road',
    slug: 'catan-settlement-road-break-errata',
    gameId: 'game-catan',
    gameName: 'Catan',
    supersedesRuleIds: ['rule-catan-longest-road'],
    effectiveDate: '2023-11-01',
    patchVersion: 'World Championship Tournament Regulations § 4.2',
    governingAuthority: 'Catan GmbH & Catan Studio International Arbiter Council',
    errataClassification: 'complete_override',
    officialRulingText: 'If Player B builds a settlement on an unoccupied intersection along Player A\'s road (obeying the standard 2-distance rule), Player A\'s road is immediately severed into two independent segments at that intersection. If neither separated segment has 5 or more continuous roads, Player A LOSES the Longest Road special victory card immediately.',
    rationale: 'Settlements represent sovereign physical settlements on the island. Roads cannot transit through a rival player\'s fortified township.',
    sourceUrl: 'https://www.catan.com/faq/longest-road-broken',
    sourceDocumentLabel: 'Catan Official Tournament Regulations § 4.2 / Rulebook FAQ 2024',
    whyVectorRAGFails: 'LLM training corpora contain thousands of forum debates claiming "roads cannot be destroyed or broken". Standard RAG averages forum opinions instead of enforcing the definitive tournament arbiter clause.',
  },
  {
    id: 'errata-gloomhaven-vertex-los',
    title: 'Isaac Childres Official FAQ v2.3: Hex-Vertex Wall Glancing Obstruction',
    slug: 'gloomhaven-faq-vertex-los-errata',
    gameId: 'game-gloomhaven',
    gameName: 'Gloomhaven',
    supersedesRuleIds: ['rule-gloomhaven-los'],
    effectiveDate: '2023-08-15',
    patchVersion: 'Official FAQ & Errata Compilation v2.3 p. 7',
    governingAuthority: 'Cephalofair Games Lead Designer (Isaac Childres)',
    errataClassification: 'timing_priority',
    officialRulingText: 'A sightline is considered obstructed and Line of Sight is INVALID if the line runs along any portion of a wall line, or touches any vertex (corner) shared by two wall segments, even if that vertex only touches the line at a single infinitesimally small geometric point.',
    rationale: 'Prevented cheese strategies where ranged characters sniped boss monsters around 90-degree stone corridors by exploiting corner-to-corner millimeter lines.',
    sourceUrl: 'https://boardgamegeek.com/thread/1687146/official-faq',
    sourceDocumentLabel: 'Gloomhaven Official FAQ v2.3 Section: Line of Sight Clarifications',
    whyVectorRAGFails: 'Naive LLMs read "from any corner to any corner without touching a wall line" and fail to comprehend whether a vertex shared between two wall hexes constitutes "touching a wall line".',
  },
  {
    id: 'errata-dnd-2024-casting-limit',
    title: '2024 Revised Rules: One Spell Slot per Turn Standard (Replacing Bonus Action Cantrip Rule)',
    slug: 'dnd-2024-revised-spell-slot-turn-rule',
    gameId: 'game-dnd',
    gameName: 'Dungeons & Dragons',
    supersedesRuleIds: ['rule-dnd-bonus-spell'],
    effectiveDate: '2024-09-17',
    patchVersion: '2024 Revised Player\'s Handbook Chapter 7 p. 238',
    governingAuthority: 'D&D Principal Rules Designer (Jeremy Crawford & Wizards of the Coast)',
    errataClassification: 'complete_override',
    officialRulingText: 'The 2014 "bonus action cantrip" restriction has been completely replaced in the 2024 Revised Rules. The new rule states: "On a turn, you can expend only ONE spell slot to cast a spell." This means if you cast a spell that does not consume a spell slot, you CAN freely cast a bonus action leveled spell slot. Conversely, Action Surge cannot be used to cast two leveled spell slots on the same turn.',
    rationale: 'Unified confusing action economy into an intuitive metric: counting expended spell slots rather than juggling action/bonus action classifications.',
    sourceUrl: 'https://www.dndbeyond.com/sources/dnd/phb-2024',
    sourceDocumentLabel: 'D&D 2024 Revised Player\'s Handbook Chapter 7: Casting Spells',
    whyVectorRAGFails: '10 years of internet content explain the 2014 rule. Vector embeddings overwhelmingly weight the 2014 version, routinely hallucinating the deprecated "cantrip-only" rule for 2024 campaign questions.',
  },
]

export const SEED_DISPUTES: DisputedScenarioRecord[] = [
  // 4 Genuine Magic: The Gathering Tournament Disputes
  {
    id: 'dispute-mtg-carnage-ward',
    title: 'Carnage Tyrant Fight Spell vs Opponent\'s Ward {2} Creature',
    slug: 'carnage-tyrant-fight-vs-ward-2',
    gameId: 'game-mtg',
    gameName: 'Magic: The Gathering',
    stakesLevel: 'finals',
    scenarioDescription: 'In the finals of a Regional Championship Qualifier (RCQ), Player A has Carnage Tyrant on the battlefield ("This spell can\'t be countered. Trample, hexproof"). Player B controls a creature with "Ward {2}". Player A casts Bushwhack targeting Carnage Tyrant and Player B\'s creature to fight. Player A is tapped out. Player B demands {2} mana, claiming that because Player A cannot pay, the fight spell is countered. Player A refuses, arguing that Carnage Tyrant says "This spell can\'t be countered", so the fight cannot be stopped by Ward.',
    playerAClaim: 'Player A argues: "Carnage Tyrant explicitly says \'This spell can\'t be countered\'. The fight is conducted by Carnage Tyrant, so Ward\'s counter instruction fails under Golden Rule CR 101.2!"',
    playerBClaim: 'Player B insists: "CR 604.3a & CR 702.21a: Carnage Tyrant\'s \'can\'t be countered\' is a static ability that applies only while Carnage Tyrant is a spell on the stack! On the battlefield, Bushwhack is an independent spell. Because you can\'t pay {2}, Ward counters Bushwhack!"',
    naiveLLMAnswer: '❌ Naive LLM Answer (Hallucinated): "Player A is correct because Carnage Tyrant has the text \'This spell can\'t be countered\', which protects it from opponent counter abilities like Ward."',
    groundedArbiterRuling: '⚖️ OFFICIAL ARBITER VERDICT (UPHELD FOR PLAYER B): Under Magic Comprehensive Rules CR 604.3a, CR 113.6, and CR 702.21a: Carnage Tyrant\'s "This spell can\'t be countered" functions SOLELY while it is a spell on the stack. Once on the battlefield, Carnage Tyrant is a creature permanent. The fight spell (Bushwhack) is an independent spell that does NOT inherit uncounterable status. Because Player A cannot pay the {2} Ward cost, Ward\'s triggered ability counters Bushwhack. The fight is prevented and Bushwhack is sent to the graveyard. Player A\'s objection is OVERRULED.',
    winnerResolution: 'player_b',
    governingRuleId: 'rule-mtg-ward',
    governingErrataId: 'errata-mtg-ward-fight',
    provenanceHash: 'sha256-mtg-cr604-3a-ward-cert',
  },
  {
    id: 'dispute-mtg-deathtouch-trample-indestructible',
    title: '6/6 Deathtouch + Trample Attacker vs 10/10 Indestructible Blocker',
    slug: 'deathtouch-trample-vs-indestructible-blocker',
    gameId: 'game-mtg',
    gameName: 'Magic: The Gathering',
    stakesLevel: 'finals',
    scenarioDescription: 'Player A attacks with a 6/6 creature possessing both Deathtouch and Trample. Player B blocks with a 10/10 creature with Indestructible (Darksteel Colossus). Player A assigns 1 point of combat damage to the 10/10 blocker and tramples the remaining 5 damage directly to Player B\'s life total. Player B calls a judge, claiming that because Indestructible prevents death from lethal damage, 1 damage is not lethal, and Player A must assign all 6 damage to the blocker before any trample can occur.',
    playerAClaim: 'Player A argues: "Under CR 702.2c, any nonzero damage from deathtouch is lethal damage for assignment purposes. I assign 1 lethal damage to the blocker, and the remaining 5 tramples through to your face!"',
    playerBClaim: 'Player B insists: "My creature is Indestructible! 1 damage does not destroy it, so it is not lethal damage. You cannot trample past an indestructible creature until you absorb its full 10 toughness!"',
    naiveLLMAnswer: '❌ Naive LLM Answer (Hallucinated): "Player B is correct because an Indestructible creature cannot be destroyed by lethal damage, so an attacking creature cannot trample over it without assigning damage equal to its full toughness."',
    groundedArbiterRuling: '⚖️ OFFICIAL ARBITER VERDICT (UPHELD FOR PLAYER A): Under Comprehensive Rules CR 702.2c and CR 702.19b: Deathtouch defines ANY nonzero amount of combat damage as "lethal damage" for damage assignment purposes. The attacking player is only required to assign lethal damage to each blocker before trampling excess power. The fact that Indestructible (CR 702.12b) subsequently prevents the blocker from being destroyed during state-based actions is completely irrelevant to assignment. Player A legally assigns 1 damage to the 10/10 blocker and 5 damage tramples directly to Player B\'s life total.',
    winnerResolution: 'player_a',
    governingRuleId: 'rule-mtg-deathtouch',
    governingErrataId: 'errata-mtg-deathtouch-trample',
    provenanceHash: 'sha256-mtg-cr702-2c-trample-cert',
  },
  {
    id: 'dispute-mtg-bloodmoon-saga',
    title: 'Blood Moon Resolved with Active Urza\'s Saga on the Battlefield',
    slug: 'blood-moon-vs-urzas-saga-graveyard-sacrifice',
    gameId: 'game-mtg',
    gameName: 'Magic: The Gathering',
    stakesLevel: 'regional',
    scenarioDescription: 'In a Modern RCQ, Player A has Urza\'s Saga on the battlefield with 2 lore counters on it. Player B resolves Blood Moon ("Nonbasic lands are Mountains"). Player A claims Urza\'s Saga is now a Mountain that taps for {R} and stays on the battlefield indefinitely with its 2 counters. Player B calls a judge, claiming Urza\'s Saga must be sacrificed to the graveyard immediately.',
    playerAClaim: 'Player A argues: "Blood Moon says nonbasic lands are Mountains. My land is just a Mountain now with 2 counters on it. It taps for red mana and stays in play!"',
    playerBClaim: 'Player B insists: "CR 305.7 strips its chapter abilities, but it remains a Saga. Under CR 704.5s, its max chapter number is now 0. Because 2 counters >= 0, state-based actions force it to be sacrificed immediately!"',
    naiveLLMAnswer: '❌ Naive LLM Answer (Hallucinated): "Player A keeps Urza\'s Saga on the battlefield because Blood Moon turns nonbasic lands into Mountains, giving it the ability to tap for Red mana while retaining its permanency."',
    groundedArbiterRuling: '⚖️ OFFICIAL ARBITER VERDICT (UPHELD FOR PLAYER B): Under CR 305.7 (Layer 4 Subtype Overwrite) and CR 704.5s (Saga State-Based Actions): Blood Moon replaces Urza\'s Saga\'s land subtypes with Mountain, causing it to lose all abilities printed in its text box. However, it still retains the card type "Enchantment Land — Urza\'s Saga". Under CR 704.5s, if a Saga has lore counters >= its greatest chapter number, its controller sacrifices it. Because all chapter abilities were removed, its greatest chapter number is 0. Since 2 lore counters >= 0, Urza\'s Saga is IMMEDIATELY SACRIFICED to the graveyard.',
    winnerResolution: 'player_b',
    governingRuleId: 'rule-mtg-land-overwrite',
    governingErrataId: 'errata-mtg-blood-moon-saga',
    provenanceHash: 'sha256-mtg-cr305-7-bloodmoon-saga-cert',
  },
  {
    id: 'dispute-mtg-dressdown-oracle',
    title: 'Dress Down Cast in Response to Thassa\'s Oracle ETB Trigger',
    slug: 'dress-down-vs-thassas-oracle-etb-trigger',
    gameId: 'game-mtg',
    gameName: 'Magic: The Gathering',
    stakesLevel: 'finals',
    scenarioDescription: 'Player A casts Thassa\'s Oracle with zero cards in library. It enters the battlefield, and its triggered ability ("When Thassa\'s Oracle enters the battlefield, look at the top X cards... if X is greater than or equal to cards in library, you win the game") goes on the stack. In response, Player B flashes in Dress Down ("Creatures lose all abilities"). Player B claims that because Thassa\'s Oracle has lost all abilities, the trigger is disabled and Player A does not win.',
    playerAClaim: 'Player A argues: "CR 113.7a states abilities on the stack exist independently of their source. Dress Down takes away abilities from the creature, but the trigger is already on the stack and will still resolve!"',
    playerBClaim: 'Player B insists: "Dress Down says creatures lose all abilities. Thassa\'s Oracle has no abilities on the battlefield, so its win condition trigger is null and void!"',
    naiveLLMAnswer: '❌ Naive LLM Answer (Hallucinated): "Player B is right because Dress Down states creatures lose all abilities, which disables Thassa\'s Oracle from winning the game when the trigger resolves."',
    groundedArbiterRuling: '⚖️ OFFICIAL ARBITER VERDICT (UPHELD FOR PLAYER A): Under Comprehensive Rules CR 113.7a and CR 603.3: Abilities on the stack exist completely independently of their source permanent. Dress Down\'s continuous effect in Layer 6 removes abilities from creature permanents on the battlefield, but it does NOT counter or remove abilities that have already been put on the stack. When the ETB trigger resolves, it checks Player A\'s devotion and library size (0), and Player A WINS THE GAME. Player B\'s objection is OVERRULED.',
    winnerResolution: 'player_a',
    governingRuleId: 'rule-mtg-stack-independence',
    governingErrataId: 'errata-mtg-dressdown-etb',
    provenanceHash: 'sha256-mtg-cr113-7a-dressdown-cert',
  },

  // Supporting Games Disputes
  {
    id: 'dispute-wh40k-infiltrator-deepstrike',
    title: 'Terminator Deep Strike within 9" of Space Marine Infiltrators with Omni-Scrambler',
    slug: 'terminator-deepstrike-vs-infiltrators-omni-scrambler',
    gameId: 'game-wh40k',
    gameName: 'Warhammer 40,000',
    stakesLevel: 'regional',
    scenarioDescription: 'Round 4 of a Major ITC Tournament. Player A arrives from Reserves with a 10-man Terminator Squad using Deep Strike, positioning them 9.1 inches away from Player B\'s objective marker holding Space Marine Infiltrators. Player B stops the game, claiming their Infiltrator unit possesses an Omni-Scrambler preventing arrivals within 12 inches.',
    playerAClaim: 'Player A insists: "Core Rules page 39 says Deep Strike is more than 9 inches. My unit has the Deep Strike keyword and I am 9.1 inches away!"',
    playerBClaim: 'Player B argues: "The 2024 Balance Dataslate and Infiltrator datasheet explicitly state that enemy units cannot arrive from reserves within 12 inches. The unit-specific rule overrides the core book!"',
    naiveLLMAnswer: '❌ Naive LLM Answer: "Player A is correct. Under 10th edition rules, Deep Strike units can always arrive anywhere more than 9 inches horizontally away from all enemy models."',
    groundedArbiterRuling: '⚖️ OFFICIAL ARBITER VERDICT (UPHELD FOR PLAYER B): Under Warhammer 40k Rules Commentary & Balance Dataslate 2024: Unit-specific exclusion auras (Omni-Scramblers) take precedence over general Core Rules p. 39. Deep strike arrivals within 12" of an active Infiltrator model are ILLEGAL. Player A must relocate the Terminator squad outside the 12" bubble or return to reserves.',
    winnerResolution: 'player_b',
    governingRuleId: 'rule-wh40k-deepstrike',
    governingErrataId: 'errata-wh40k-omni-scrambler',
    provenanceHash: 'sha256-wh40k-dataslate-omni-cert',
  },
  {
    id: 'dispute-catan-longest-road-cut',
    title: 'Sudden Settlement Built in the Middle of an Opponent\'s 7-Segment Longest Road',
    slug: 'catan-settlement-bisects-longest-road',
    gameId: 'game-catan',
    gameName: 'Catan',
    stakesLevel: 'casual_dispute',
    scenarioDescription: 'Casual tournament table at a local board game cafe. Player A holds the Longest Road card (7 continuous segments). Player B uses their turn to build a legal settlement on an unoccupied vertex along Player A\'s road path. Player B announces: "Player A\'s road is severed into 4 and 3 segments. Since 4 is less than 5, Player A loses the 2 victory points immediately!" Player A threatens to flip the table.',
    playerAClaim: 'Player A protests: "You cannot destroy my roads! My roads are already built and continuous. Your settlement only belongs to you, it does not erase my road segments!"',
    playerBClaim: 'Player B insists: "World Championship Regulations Section 4.2 states that an opponent settlement bisects your road into two separate branches. You don\'t have 5 continuous segments anymore!"',
    naiveLLMAnswer: '❌ Naive LLM Answer: "Player A keeps the Longest Road because road pieces once laid cannot be broken or shortened by opposing players during the game."',
    groundedArbiterRuling: '⚖️ OFFICIAL ARBITER VERDICT (UPHELD FOR PLAYER B): Under Catan Tournament Regulations § 4.2: Building a settlement on an open intersection splits an opponent\'s road. Player A\'s continuous length dropped from 7 to 4. Because 4 is below the minimum threshold of 5, the Longest Road victory card is forfeited immediately.',
    winnerResolution: 'player_b',
    governingRuleId: 'rule-catan-longest-road',
    governingErrataId: 'errata-catan-road-broken',
    provenanceHash: 'sha256-catan-sec-4-2-arbiter-cert',
  },
  {
    id: 'dispute-gloomhaven-corner-hex-los',
    title: 'Scoundrel Ranged Bow Shot Grazing a Double-Wall Hex Vertex Corner',
    slug: 'gloomhaven-scoundrel-bow-wall-corner-los',
    gameId: 'game-gloomhaven',
    gameName: 'Gloomhaven',
    stakesLevel: 'casual_dispute',
    scenarioDescription: 'A high-level cooperative scenario where failure means permadeath. The Scoundrel player wants to make a crucial ranged attack on an Elite Bandit Archer. Drawing a ruler from the Scoundrel\'s bottom-left hex vertex to the Bandit\'s top-right vertex grazes the exact geometric corner where two solid stone wall hexes intersect.',
    playerAClaim: 'Scoundrel Player: "Rulebook page 19 says draw a line from any corner to any corner without touching a wall line. My line only touches a vertex corner point, not the line of the wall itself!"',
    playerBClaim: 'Monster Controller: "Isaac Childres\' official FAQ clearly states that wall vertices block line of sight completely if shared by two wall segments!"',
    naiveLLMAnswer: '❌ Naive LLM Answer: "Line of sight is valid. As long as the line connects two corners without passing through the body of an obstacle hex, the attack can proceed."',
    groundedArbiterRuling: '⚖️ OFFICIAL ARBITER VERDICT (UPHELD FOR MONSTER CONTROLLER / PLAYER B): Under Official Gloomhaven Comprehensive FAQ v2.3 p. 7: Touching a vertex corner shared by two wall segments BLOCKS line of sight. Sightlines cannot pass infinitesimally through corner seams. The ranged attack has NO line of sight and cannot be declared from that position.',
    winnerResolution: 'player_b',
    governingRuleId: 'rule-gloomhaven-los',
    governingErrataId: 'errata-gloomhaven-vertex-los',
    provenanceHash: 'sha256-gloomhaven-faq-2-3-cert',
  },
  {
    id: 'dispute-dnd-misty-step-fireball',
    title: 'Casting Misty Step (Bonus Action) then Action Surge Fireball in 2024 D&D Rules',
    slug: 'dnd-2024-misty-step-action-surge-fireball',
    gameId: 'game-dnd',
    gameName: 'Dungeons & Dragons',
    stakesLevel: 'finals',
    scenarioDescription: 'Convention competitive delve. An Eldritch Knight multiclass wizard casts Misty Step using a 2nd-level spell slot as a bonus action to teleport across a chasm, then pops Action Surge to cast Fireball using a 3rd-level spell slot. The Dungeon Master says: "Under the spellcasting rules, you can only cast a cantrip as your action if you cast a bonus action spell!"',
    playerAClaim: 'Player: "We are playing the 2024 Revised Rules! The 2014 bonus action cantrip rule is deleted. The new rule is One Spell Slot per turn!"',
    playerBClaim: 'DM: "Even if it is the 2024 rule, you are casting Misty Step (a leveled slot) AND Fireball (a leveled slot). Both expend spell slots on the same turn, so it\'s still illegal!"',
    naiveLLMAnswer: '❌ Naive LLM Answer: "The DM is right because of the bonus action cantrip rule in the Player\'s Handbook page 202."',
    groundedArbiterRuling: '⚖️ OFFICIAL ARBITER VERDICT (SPLIT - DM RULING UPHELD, BUT FOR 2024 REASON): The player is correct that the 2014 "bonus action cantrip" rule no longer exists in the 2024 Revised PHB. HOWEVER, under the new 2024 Chapter 7 rule ("One Spell Slot per Turn"), a character cannot expend more than ONE spell slot on their turn, regardless of Action Surge. Because Misty Step AND Fireball both consume spell slots, casting both on the same turn is ILLEGAL under 2024 rules.',
    winnerResolution: 'split',
    governingRuleId: 'rule-dnd-bonus-spell',
    governingErrataId: 'errata-dnd-2024-casting-limit',
    provenanceHash: 'sha256-dnd-2024-phb-ch7-cert',
  },
]
